# Generated by Django 4.2.9 on 2024-02-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_batterystatus_ride_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batterystatus',
            old_name='charging_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='batterystatus',
            name='health',
        ),
        migrations.RemoveField(
            model_name='batterystatus',
            name='level',
        ),
        migrations.RemoveField(
            model_name='rideevent',
            name='distanceTravelled',
        ),
        migrations.RemoveField(
            model_name='rideevent',
            name='energyConsumed',
        ),
        migrations.AddField(
            model_name='batterystatus',
            name='capacity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
