# Generated by Django 4.2.9 on 2024-02-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_charging_status_batterystatus_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterymodel',
            name='capacity',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='batterystatus',
            name='capacity',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
