# Generated by Django 4.2.9 on 2024-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_batterymodel_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance_travelled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trip',
            name='energy_consumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
