# Generated by Django 4.2.9 on 2024-03-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_trip_distance_travelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='swapevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bike_id__isnull', False), ('station_id__isnull', True)), models.Q(('bike_id__isnull', True), ('station_id__isnull', False)), _connector='OR'), name='station_or_bike'),
        ),
    ]
