# Generated by Django 4.2.9 on 2024-03-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_swapevent_timestamp_swapevent_station_or_bike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='license_plate',
            new_name='license_number',
        ),
    ]
