# Generated by Django 4.2.9 on 2024-03-26 04:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_license_plate_bike_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='battery_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, default=list, size=2),
        ),
    ]
