# Generated by Django 4.2.9 on 2024-03-26 05:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bike_battery_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='battery_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, default=list, size=12),
        ),
    ]
