# Generated by Django 4.2.9 on 2024-03-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_station_battery_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='number',
            field=models.CharField(db_index=True, default='', max_length=17, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='number',
            field=models.CharField(db_index=True, default='', max_length=17, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
